FROM --platform=linux/arm64 nvcr.io/nvidia/tensorrt-llm/release:1.0.0rc4@sha256:344a0906c03c5873d067b8c454b8225c81083a25325e254a4a4522dab01c347c

# Install gcloud CLI for ARM64
ENV CLOUD_SDK_VERSION=460.0.0
ENV PATH="/opt/google-cloud-sdk/bin:${PATH}"
RUN apt-get update -y && \
    apt-get install -y curl python3-minimal && \
    curl -O "https://dl.google.com/dl/cloudsdk/channels/rapid/downloads/google-cloud-sdk-${CLOUD_SDK_VERSION}-linux-arm.tar.gz" && \
    tar -xf "google-cloud-sdk-${CLOUD_SDK_VERSION}-linux-arm.tar.gz" -C /opt && \
    rm "google-cloud-sdk-${CLOUD_SDK_VERSION}-linux-arm.tar.gz" && \
    /opt/google-cloud-sdk/install.sh \
      --bash-completion=false \
      --path-update=false \
      --usage-reporting=false \
      --quiet

WORKDIR /app/tensorrt_llm
COPY scripts/run_model_benchmarks.sh .
COPY scripts/prepare_dataset.py ./benchmarks/cpp/
COPY scripts/prepare_synthetic_data.py ./benchmarks/cpp/utils/
COPY configs/ ./configs/

#RUN chmod +x trtllm-bench.sh
ENTRYPOINT ["/bin/sh", "-c"]


